# Auto-generated configuration file

SCRAPING = [
    {
        'directory': 'PDFs/brott-et-al-2011-2011-asa-accf-aha-aann-aans-acr-asnr-cns-saip-scai-sir-snis-svm-svs-guideline-on-the-management-of',
        'guideline_xml': 'brott-et-al-2011-2011-asa-accf-aha-aann-aans-acr-asnr-cns-saip-scai-sir-snis-svm-svs-guideline-on-the-management-of.xml',
        'cit_version': 2,
        'guideline_version': 2,
        'left_down': 70,
        'left_up': 100,
    },
    {
        'directory': 'PDFs/ommen-et-al-2024-2024-aha-acc-amssm-hrs-paces-scmr-guideline-for-the-management-of-hypertrophic-cardiomyopathy',
        'guideline_xml': 'ommen-et-al-2024-2024-aha-acc-amssm-hrs-paces-scmr-guideline-for-the-management-of-hypertrophic-cardiomyopathy.xml',
        'cit_version': 2,
        'guideline_version': 2,
        'left_down': 80,
        'left_up': 90,
    },
    {
        'directory': 'PDFs/gornik-et-al-2024-2024-acc-aha-aacvpr-apma-abc-scai-svm-svn-svs-sir-vess-guideline-for-the-management-of-lower',
        'guideline_xml': 'gornik-et-al-2024-2024-acc-aha-aacvpr-apma-abc-scai-svm-svn-svs-sir-vess-guideline-for-the-management-of-lower.xml',
        'cit_version': 2,
        'guideline_version': 2,
        'left_down': 80,
        'left_up': 90,
    },
    {
        'directory': 'PDFs/lawton-et-al-2021-2021-acc-aha-scai-guideline-for-coronary-artery-revascularization',
        'guideline_xml': 'lawton-et-al-2021-2021-acc-aha-scai-guideline-for-coronary-artery-revascularization.xml',
        'cit_version': 1,
        'guideline_version': 2,
        'left_down': 80,
        'left_up': 90,
    },
    {
        'directory': 'PDFs/isselbacher-et-al-2022-2022-acc-aha-guideline-for-the-diagnosis-and-management-of-aortic-disease',
        'guideline_xml': 'isselbacher-et-al-2022-2022-acc-aha-guideline-for-the-diagnosis-and-management-of-aortic-disease.xml',
        'cit_version': 1,
        'guideline_version': 2,
        'left_down': 70,
        'left_up': 80,
    },
    {
        'directory': 'PDFs/page-et-al-2015-2015-acc-aha-hrs-guideline-for-the-management-of-adult-patients-with-supraventricular-tachycardia',
        'guideline_xml': 'page-et-al-2015-2015-acc-aha-hrs-guideline-for-the-management-of-adult-patients-with-supraventricular-tachycardia.xml',
        'cit_version': 2,
        'guideline_version': 2,
        'left_down': 60,
        'left_up': 70,
    },
    {
        'directory': 'PDFs/joglar-et-al-2023-2023-acc-aha-accp-hrs-guideline-for-the-diagnosis-and-management-of-atrial-fibrillation',
        'guideline_xml': 'joglar-et-al-2023-2023-acc-aha-accp-hrs-guideline-for-the-diagnosis-and-management-of-atrial-fibrillation.xml',
        'cit_version': 1,
        'guideline_version': 2,
        'left_down': 70,
        'left_up': 80,
    },
    {
        'directory': 'PDFs/goff-et-al-2013-2013-acc-aha-guideline-on-the-assessment-of-cardiovascular-risk',
        'guideline_xml': 'goff-et-al-2013-2013-acc-aha-guideline-on-the-assessment-of-cardiovascular-risk.xml',
        'cit_version': 2,
        'guideline_version': 2,
        'left_down': 80,
        'left_up': 90,
    },
    {
        'directory': 'PDFs/arnett-et-al-2019-2019-acc-aha-guideline-on-the-primary-prevention-of-cardiovascular-disease',
        'guideline_xml': 'arnett-et-al-2019-2019-acc-aha-guideline-on-the-primary-prevention-of-cardiovascular-disease.xml',
        'cit_version': 1,
        'guideline_version': 2,
        'left_down': 70,
        'left_up': 80,
    },
    {
        'directory': 'PDFs/whelton-et-al-2017-2017-acc-aha-aapa-abc-acpm-ags-apha-ash-aspc-nma-pcna-guideline-for-the-prevention-detection',
        'guideline_xml': 'whelton-et-al-2017-2017-acc-aha-aapa-abc-acpm-ags-apha-ash-aspc-nma-pcna-guideline-for-the-prevention-detection.xml',
        'cit_version': 1,
        'guideline_version': 2,
        'left_down': 70,
        'left_up': 80,
    },
    {
        'directory': 'PDFs/amsterdam-et-al-2014-2014-aha-acc-guideline-for-the-management-of-patients-with-non-st-elevation-acute-coronary',
        'guideline_xml': 'amsterdam-et-al-2014-2014-aha-acc-guideline-for-the-management-of-patients-with-non-st-elevation-acute-coronary.xml',
        'cit_version': 2,
        'guideline_version': 2,
        'left_down': 70,
        'left_up': 80,
    },
    {
        'directory': 'PDFs/virani-et-al-2023-2023-aha-acc-accp-aspc-nla-pcna-guideline-for-the-management-of-patients-with-chronic-coronary-disease',
        'guideline_xml': 'virani-et-al-2023-2023-aha-acc-accp-aspc-nla-pcna-guideline-for-the-management-of-patients-with-chronic-coronary-disease.xml',
        'cit_version': 1,
        'guideline_version': 2,
        'left_down': 70,
        'left_up': 80,
    },
    {
        'directory': 'PDFs/levine-et-al-2016-2016-acc-aha-guideline-focused-update-on-duration-of-dual-antiplatelet-therapy-in-patients-with',
        'guideline_xml': 'levine-et-al-2016-2016-acc-aha-guideline-focused-update-on-duration-of-dual-antiplatelet-therapy-in-patients-with.xml',
        'cit_version': 2,
        'guideline_version': 2,
        'left_down': 80,
        'left_up': 130,
    },
    {
        'directory': 'PDFs/tracy-et-al-2012-2012-accf-aha-hrs-focused-update-incorporated-into-the-accf-aha-hrs-2008-guidelines-for-device-based',
        'guideline_xml': 'tracy-et-al-2012-2012-accf-aha-hrs-focused-update-incorporated-into-the-accf-aha-hrs-2008-guidelines-for-device-based.xml',
        'cit_version': 2,
        'guideline_version': 2,
        'left_down': 80,
        'left_up': 110,
    },
    {
        'directory': 'PDFs/o-gara-et-al-2012-2013-accf-aha-guideline-for-the-management-of-st-elevation-myocardial-infarction',
        'guideline_xml': 'o-gara-et-al-2012-2013-accf-aha-guideline-for-the-management-of-st-elevation-myocardial-infarction.xml',
        'cit_version': 2,
        'guideline_version': 1,
        'left_down': 63,
        'left_up': 80,
    },
    {
        'directory': 'PDFs/shen-et-al-2017-2017-acc-aha-hrs-guideline-for-the-evaluation-and-management-of-patients-with-syncope',
        'guideline_xml': 'shen-et-al-2017-2017-acc-aha-hrs-guideline-for-the-evaluation-and-management-of-patients-with-syncope.xml',
        'cit_version': 2,
        'guideline_version': 2,
        'left_down': 80,
        'left_up': 90,
    },
    {
        'directory': 'PDFs/kusumoto-et-al-2018-2018-acc-aha-hrs-guideline-on-the-evaluation-and-management-of-patients-with-bradycardia-and',
        'guideline_xml': 'kusumoto-et-al-2018-2018-acc-aha-hrs-guideline-on-the-evaluation-and-management-of-patients-with-bradycardia-and.xml',
        'cit_version': 1,
        'guideline_version': 2,
        'left_down': 70,
        'left_up': 80,
    },
    {
        'directory': 'PDFs/gulati-et-al-2021-2021-aha-acc-ase-chest-saem-scct-scmr-guideline-for-the-evaluation-and-diagnosis-of-chest-pain',
        'guideline_xml': 'gulati-et-al-2021-2021-aha-acc-ase-chest-saem-scct-scmr-guideline-for-the-evaluation-and-diagnosis-of-chest-pain.xml',
        'cit_version': 2,
        'guideline_version': 2,
        'left_down': 70,
        'left_up': 80,
    },
    {
        'directory': 'PDFs/grundy-et-al-2018-2018-aha-acc-aacvpr-aapa-abc-acpm-ada-ags-apha-aspc-nla-pcna-guideline-on-the-management-of-blood',
        'guideline_xml': 'grundy-et-al-2018-2018-aha-acc-aacvpr-aapa-abc-acpm-ada-ags-apha-aspc-nla-pcna-guideline-on-the-management-of-blood.xml',
        'cit_version': 1,
        'guideline_version': 2,
        'left_down': 90,
        'left_up': 100,
    },
    {
        'directory': 'PDFs/eckel-et-al-2013-2013-aha-acc-guideline-on-lifestyle-management-to-reduce-cardiovascular-risk',
        'guideline_xml': 'eckel-et-al-2013-2013-aha-acc-guideline-on-lifestyle-management-to-reduce-cardiovascular-risk.xml',
        'cit_version': 2,
        'guideline_version': 2,
        'left_down': 80,
        'left_up': 100,
    },
    {
        'directory': 'PDFs/al-khatib-et-al-2018-2017-aha-acc-hrs-guideline-for-management-of-patients-with-ventricular-arrhythmias-and-the',
        'guideline_xml': 'al-khatib-et-al-2018-2017-aha-acc-hrs-guideline-for-management-of-patients-with-ventricular-arrhythmias-and-the.xml',
        'cit_version': 1,
        'guideline_version': 2,
        'left_down': 70,
        'left_up': 80,
    },
    {
        'directory': 'PDFs/stout-et-al-2018-2018-aha-acc-guideline-for-the-management-of-adults-with-congenital-heart-disease',
        'guideline_xml': 'stout-et-al-2018-2018-aha-acc-guideline-for-the-management-of-adults-with-congenital-heart-disease.xml',
        'cit_version': 1,
        'guideline_version': 2,
        'left_down': 60,
        'left_up': 70,
    },
    {
        'directory': 'PDFs/heidenreich-et-al-2022-2022-aha-acc-hfsa-guideline-for-the-management-of-heart-failure',
        'guideline_xml': 'heidenreich-et-al-2022-2022-aha-acc-hfsa-guideline-for-the-management-of-heart-failure.xml',
        'cit_version': 1,
        'guideline_version': 2,
        'left_down': 60,
        'left_up': 70,
    },
    {
        'directory': 'PDFs/smith-et-al-2011-aha-accf-secondary-prevention-and-risk-reduction-therapy-for-patients-with-coronary-and-other',
        'guideline_xml': 'smith-et-al-2011-aha-accf-secondary-prevention-and-risk-reduction-therapy-for-patients-with-coronary-and-other.xml',
        'cit_version': 1,
        'guideline_version': 1,
        'left_down': 630,
        'left_up': 670,
    },
    {
        'directory': 'PDFs/anderson-et-al-2013-management-of-patients-with-peripheral-artery-disease-%28compilation-of-2005-and-2011-accf-aha',
        'guideline_xml': 'anderson-et-al-2013-management-of-patients-with-peripheral-artery-disease-%28compilation-of-2005-and-2011-accf-aha.xml',
        'cit_version': 2,
        'guideline_version': 1,
        'left_down': 230,
        'left_up': 640,
    },
    {
        'directory': 'PDFs/thompson-et-al-2024-2024-aha-acc-acs-asnc-hrs-sca-scct-scmr-svm-guideline-for-perioperative-cardiovascular-management',
        'guideline_xml': 'thompson-et-al-2024-2024-aha-acc-acs-asnc-hrs-sca-scct-scmr-svm-guideline-for-perioperative-cardiovascular-management.xml',
        'cit_version': 2,
        'guideline_version': 2,
        'left_down': 70,
        'left_up': 80,
    },
    {
        'directory': 'PDFs/haan-et-al-2011-effectiveness-based-guidelines-for-the-prevention-of-cardiovascular-disease-in-women-2011-update',
        'guideline_xml': 'haan-et-al-2011-effectiveness-based-guidelines-for-the-prevention-of-cardiovascular-disease-in-women-2011-update.xml',
        'cit_version': 2,
        'guideline_version': 1,
        'left_down': 80,
        'left_up': 140,
    },
    {
        'directory': 'PDFs/jensen-et-al-2013-2013-aha-acc-tos-guideline-for-the-management-of-overweight-and-obesity-in-adults',
        'guideline_xml': 'jensen-et-al-2013-2013-aha-acc-tos-guideline-for-the-management-of-overweight-and-obesity-in-adults.xml',
        'cit_version': 2,
        'guideline_version': 1,
        'left_down': 80,
        'left_up': 90,
    },
    {
        'directory': 'PDFs/otto-et-al-2020-2020-acc-aha-guideline-for-the-management-of-patients-with-valvular-heart-disease',
        'guideline_xml': 'otto-et-al-2020-2020-acc-aha-guideline-for-the-management-of-patients-with-valvular-heart-disease.xml',
        'cit_version': 2,
        'guideline_version': 2,
        'left_down': 60,
        'left_up': 70,
    },
]
